In [1]:
import pandas as pd 
df=pd.read_csv("titanic-passengers.csv", sep=";")

#Preprocessing our data
def preprocess_data(new_data):
    new_data['Age'].fillna(new_data['Age'].mean(),inplace=True)
    new_data.replace({'Sex':{'male': 1,'female':0}},inplace=True)
    new_data['Cabin']=new_data.Cabin.fillna('G6')
    new_data.replace({'Survived':{'Yes': 1,'No':0}},inplace=True)
    return new_data
data=preprocess_data(df)

In [2]:
df.head()

PassengerId  Survived  Pclass                                         Name  \
0          343         0       2                   Collander, Mr. Erik Gustaf   
1           76         0       3                      Moen, Mr. Sigurd Hansen   
2          641         0       3                       Jensen, Mr. Hans Peder   
3          568         0       3  Palsson, Mrs. Nils (Alma Cornelia Berglund)   
4          672         0       1                       Davidson, Mr. Thornton   

   Sex   Age  SibSp  Parch      Ticket     Fare  Cabin Embarked  
0    1  28.0      0      0      248740  13.0000     G6        S  
1    1  25.0      0      0      348123   7.6500  F G73        S  
2    1  20.0      0      0      350050   7.8542     G6        S  
3    0  29.0      0      4      349909  21.0750     G6        S  
4    1  31.0      1      0  F.C. 12750  52.0000    B71        S

In [22]:
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

In [4]:
df.describe(include='all').T

count unique                         top freq       mean  \
PassengerId  891.0    NaN                         NaN  NaN      446.0   
Survived     891.0    NaN                         NaN  NaN   0.383838   
Pclass       891.0    NaN                         NaN  NaN   2.308642   
Name           891    891  Collander, Mr. Erik Gustaf    1        NaN   
Sex          891.0    NaN                         NaN  NaN   0.647587   
Age          891.0    NaN                         NaN  NaN  29.699118   
SibSp        891.0    NaN                         NaN  NaN   0.523008   
Parch        891.0    NaN                         NaN  NaN   0.381594   
Ticket         891    681                    CA. 2343    7        NaN   
Fare         891.0    NaN                         NaN  NaN  32.204208   
Cabin          891    147                          G6  691        NaN   
Embarked       889      3                           S  644        NaN   

                    std   min     25%        50%    75%       max  
PassengerId  257.353842   1.0   223.5      446.0  668.5     891.0  
Survived       0.486592   0.0     0.0        0.0    1.0       1.0  
Pclass         0.836071   1.0     2.0        3.0    3.0       3.0  
Name                NaN   NaN     NaN        NaN    NaN       NaN  
Sex             0.47799   0.0     0.0        1.0    1.0       1.0  
Age           13.002015  0.42    22.0  29.699118   35.0      80.0  
SibSp          1.102743   0.0     0.0        0.0    1.0       8.0  
Parch          0.806057   0.0     0.0        0.0    0.0       6.0  
Ticket              NaN   NaN     NaN        NaN    NaN       NaN  
Fare          49.693429   0.0  7.9104    14.4542   31.0  512.3292  
Cabin               NaN   NaN     NaN        NaN    NaN       NaN  
Embarked            NaN   NaN     NaN        NaN    NaN       NaN

In [5]:
Age_Cat = [0, 5, 17, 25, 50, 80]
labels = ['Infant', 'Kid', 'Young', 'Adult', 'Old']
df['Age'] = pd.cut(df['Age'], bins = Age_Cat, labels=labels)

In [6]:
df.head()

PassengerId  Survived  Pclass                                         Name  \
0          343         0       2                   Collander, Mr. Erik Gustaf   
1           76         0       3                      Moen, Mr. Sigurd Hansen   
2          641         0       3                       Jensen, Mr. Hans Peder   
3          568         0       3  Palsson, Mrs. Nils (Alma Cornelia Berglund)   
4          672         0       1                       Davidson, Mr. Thornton   

   Sex    Age  SibSp  Parch      Ticket     Fare  Cabin Embarked  
0    1  Adult      0      0      248740  13.0000     G6        S  
1    1  Young      0      0      348123   7.6500  F G73        S  
2    1  Young      0      0      350050   7.8542     G6        S  
3    0  Adult      0      4      349909  21.0750     G6        S  
4    1  Adult      1      0  F.C. 12750  52.0000    B71        S

In [7]:
df['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [8]:
df=df.fillna({'Embarked' : 'S'})

In [9]:
df['Embarked'].unique()

array(['S', 'C', 'Q'], dtype=object)

In [10]:
df['Fare'].describe()

count    891.000000
mean      32.204208
std       49.693429
min        0.000000
25%        7.910400
50%       14.454200
75%       31.000000
max      512.329200
Name: Fare, dtype: float64

In [11]:
Categories = [-1, 7.910400, 14.4542, 31, 512.330]
labels = ['low', 'medium-low', 'medium', 'high']
df['Fare'] = pd.cut(df["Fare"], bins = Categories, labels = labels)

In [12]:
df['Fare'].unique()

['medium-low', 'low', 'medium', 'high']
Categories (4, object): ['low' < 'medium-low' < 'medium' < 'high']

In [13]:
Features = ['Fare', 'Age', 'Embarked']
Feat_Data = pd.get_dummies(df[Features])

In [191]:
Feat_Data.head()

Fare_low  Fare_medium-low  Fare_medium  Fare_high  Age_Infant  Age_Kid  \
0         0                1            0          0           0        0   
1         1                0            0          0           0        0   
2         1                0            0          0           0        0   
3         0                0            1          0           0        0   
4         0                0            0          1           0        0   

   Age_Young  Age_Adult  Age_Old  Embarked_C  Embarked_Q  Embarked_S  
0          0          1        0           0           0           1  
1          1          0        0           0           0           1  
2          1          0        0           0           0           1  
3          0          1        0           0           0           1  
4          0          1        0           0           0           1

In [14]:
df = pd.concat([df, Feat_Data], axis = 1)
df.drop(Features, axis=1, inplace=True)

In [15]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'SibSp', 'Parch',
       'Ticket', 'Cabin', 'Fare_low', 'Fare_medium-low', 'Fare_medium',
       'Fare_high', 'Age_Infant', 'Age_Kid', 'Age_Young', 'Age_Adult',
       'Age_Old', 'Embarked_C', 'Embarked_Q', 'Embarked_S'],
      dtype='object')

In [17]:
X=df.drop(['Survived','Name','Cabin','Ticket'],axis=1)
Y=df['Survived']
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [18]:
log_reg = LogisticRegression()
log_reg.fit(X_train, Y_train)
Y_pred = log_reg.predict(X_test)
Y_pred

C:\Users\hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1], dtype=int64)

In [19]:
accuracy_score(Y_pred, Y_test)

0.8268156424581006

In [20]:
confusion_matrix(Y_pred, Y_test)

array([[107,  20],
       [ 11,  41]], dtype=int64)

We try to make a prediction with our built model :)

In [199]:
import numpy as np

In [208]:
Array_test=np.array([[69, 3,  1, 0, 
        1, 0, 0, 0,
       0, 0, 0, 0, 1,
       0, 0, 1, 1]]) #Prediction for an old Male

In [209]:
Pred_test = log_reg.predict(Array_test)
Pred_test

array([0], dtype=int64)

In [214]:
Array_test=np.array([[69, 3,  0, 0, 
        1, 0, 0, 0,
       0, 0, 0, 0, 1,
       0, 0, 1, 1]]) #Prediction for an old Female

In [215]:
Pred_test = log_reg.predict(Array_test)
Pred_test

array([1], dtype=int64)

### ROC-AUC 

ROC-AUC : Metric extracted from the confusion matrix.
Receiver Operator Characteristic (ROC) curve is an evaluation metric for binary classification problems.

In [23]:
sklearn.metrics.roc_auc_score(Y_test, Y_pred)

0.7894554042789664